// This file is auto-generated by 'dalila routes generate'
// Do not edit manually - your changes will be overwritten

import type { RouteTable } from 'dalila/router';
import { fromHtml } from 'dalila';

const layout_html = `<div class="app-shell">
  <header class="app-header">
    <div>
      <h1>Dalila Router App</h1>
      <p>File-based routing starter template</p>
    </div>
    <nav class="app-nav">
      <a d-link="/">Home</a>
      <a d-link="/about">About</a>
    </nav>
  </header>

  <main class="app-main" data-slot="children"></main>
</div>
`;
const page_html = `<section class="card">
  <h2>Counter: {count}</h2>
  <p>Doubled: {doubled}</p>

  <div class="buttons">
    <button type="button" d-on-click="decrement">-</button>
    <button type="button" d-on-click="increment">+</button>
  </div>
</section>

<section class="card">
  <p when={isEven}>The count is even.</p>
  <p when={isOdd}>The count is odd.</p>
</section>
`;
const about_page_html = `<section class="card">
  <h2>About</h2>
  <p>This starter uses file-based routes from <code>src/app</code>.</p>
  <p>Use <code>npm run routes</code> after changing route files.</p>
</section>
`;

const page_lazy = () => import('./src/app/page.js');

export const routes: RouteTable[] = [
  {
    path: '/',
    layout: (ctx, children) => fromHtml(layout_html, { data: { ...(ctx.params as Record<string, unknown>), params: ctx.params, query: ctx.query.toString(), path: ctx.path, fullPath: ctx.fullPath }, children, scope: ctx.scope }),
    children: [
      { path: '', view: (ctx, data) => fromHtml(page_html, { data: { ...(ctx.params as Record<string, unknown>), ...((data ?? {}) as Record<string, unknown>), params: ctx.params, query: ctx.query.toString(), path: ctx.path, fullPath: ctx.fullPath }, scope: ctx.scope }), loader: (...args: any[]) => page_lazy().then(mod => {
      const exported = (mod as any).loader;
      if (typeof exported === 'function') {
        return exported(...args);
      }
      return undefined;
    }) },
      {
        path: 'about',
        view: (ctx) => fromHtml(about_page_html, { data: { ...(ctx.params as Record<string, unknown>), params: ctx.params, query: ctx.query.toString(), path: ctx.path, fullPath: ctx.fullPath }, scope: ctx.scope }),
      }
    ]
  }
];
