// This file is auto-generated by 'dalila routes generate'
// Do not edit manually - your changes will be overwritten

import type { RouteManifestEntry } from 'dalila/router';

export const routeManifest: RouteManifestEntry[] = [
  {
    id: 'root',
    pattern: '/',
    score: 1000,
    paramKeys: [],
    tags: [],
    modules: ["./src/app/page.js"],
    load: () => import('./src/app/page.js').then(() => undefined)
  },
  {
    id: 'about',
    pattern: '/about',
    score: 301,
    paramKeys: [],
    tags: [],
    modules: ["./src/app/page.js"],
    load: () => import('./src/app/page.js').then(() => undefined)
  },
];

const manifestById = new Map(routeManifest.map(route => [route.id, route]));

export function getRouteManifestEntry(id: string): RouteManifestEntry | undefined {
  return manifestById.get(id);
}

export async function prefetchRouteById(id: string): Promise<void> {
  const entry = manifestById.get(id);
  if (!entry) return;
  await entry.load();
}
